### ISSUE TITLE
Play-Json Interop Example

### ISSUE THREAD

**Issue by mslinn** [non/jawn#30]
Is there an example of using Jawn with Play Framework 2? For example, obtaining `play.api.libs.json.JsValue` from a request body, and doing something with it using Jawn:

````
def parseJson = Action(parse.json) { implicit request =>
  val body: JsValue = request.body
  Ok(body)
}
````

**Comment by virtualirfan** [comment]
+1

**Comment by non** [comment]
Sorry for the delayed response, I saw this but forgot to get back to it.

The short answer is: not that I know of. Currently most people I know using Jawn are using the parser. I don't have great support from translating a different AST (e.g. play's) into Jawn's AST.

What sort of AST operations are you interested in? Most of the features that make Jawn special (e.g. async parsing) happen when going from `String => AST`.

**Comment by mslinn** [comment]
So there is no use case.
