### ISSUE TITLE
jawn-play for Play 2.4.x

### ISSUE THREAD

**Issue by drbild** [non/jawn#41]
Are there plans to support Play 2.4.x?

Play's `JsObject` constructor parameter changed from a `Seq` to a `Map` (the `Seq` version is now on the companion object). `jawn` is compiled for the old version, leading to `MethodNotFound` exceptions.

**Comment by non** [comment]
@drbild It should be very easy to update. If you'd like to provide a PR, I'd be happy to merge it. Otherwise I'll get to it sometime soon. In any case, thanks for the heads-up. I rely on other people to let me know when the third-party library support needs updating. :wink:

**Comment by drbild** [comment]
Ok, I'll submit a PR.  It's just updating the dependency and recompiling.  No change to jawn code.

The published jars will no longer be compatible with Play 2.3.x.  I don't know if that's a concern.

**Comment by non** [comment]
I mostly just support whatever the current stable version seems to be. The compat projects are quite small, so if someone needs a specific version which is not supported they can either use an older version of Jawn or roll their own `Facade[J]` instance.
