### ISSUE TITLE
Number parsing doesn't match the spec

### ISSUE THREAD

**Issue by travisbrown** [non/jawn#47]
`".1"` is correctly rejected, but `"-.1"` gets parsed successfully:

```
scala> jawn.Parser.parseFromString("-.1")(jawn.ast.JawnFacade)
res0: scala.util.Try[jawn.ast.JValue] = Success(-.1)
```

I wanted to confirm that this is a bug and not intentional before I start looking into why it happens.

**Comment by non** [comment]
This is definitely a bug -- I'll try to take a look and figure out what is going on.
