### ISSUE TITLE
Argonaut 6.2: where should it go?

### ISSUE THREAD

**Issue by rossabaker** [non/jawn#49]
Argonaut 6.2-M1 has been released.  A facade should be trivial enough, but where does it go?

* Here, alongside 6.1 support?
* Here, in replacement of 6.1 support?
* Argonaut?
* A third-party glue microlibrary?

**Comment by non** [comment]
Hi @rossabaker I had missed this issue somehow.

I'm assuming 6.2 is different enough that it would not be a compatible change to update *jawn-argonaut*? I'm happy to move the old facade to *jawn-argonaut-pre62* or to release the new one as *jawn-argonaut62* for now and change their names later.

If Argonaut wants to distribute the facades that makes my life a bit easier, but I don't have a sense of whether they are open to that. If you are interested in maintaining a third-party library I would be fine with that, but I feel like an advantage of support being in Jawn or the library is that the version numbers match at least one of the projects involved.

Anyway, let me know what you think and I can take whatever action makes sense.

**Comment by rossabaker** [comment]
It's source compatible, but binary incompatible, for Jawn's needs.  I scratched my itch by copying it into http4s, but that's not the right long term solution.

For tiny glue modules like this, it's nice when they live in the faster evolving library.  That's Argonaut in this case.  I'll see if Argonaut would welcome a pull request.

**Comment by rossabaker** [comment]
Solved by argonaut-io/argonaut#219.
