### ISSUE TITLE
Introduce sbt-doge but keep sbt-release working

### ISSUE THREAD

**Issue by non** [non/jawn#57]
I want to introduce sbt-doge. We will need it to add support for 2.12.0-RC1, and also so we can start dropping 2.10 from our support projects as their respective JSON libraries drop 2.10 support.

However, it doesn't work out-of-the-box with sbt-release.

@eed3si9n pointed me at the [play build](https://github.com/playframework/playframework/blob/master/framework/project/Release.scala) which seems to use both, but has other structural differences.

I'll try to look at this soon, but if anyone is dying to become a Jawn contributor and knows a bit about SBT this is your chance!

![b9710fdfde64c6688492dc87be797da2](https://cloud.githubusercontent.com/assets/218045/18318394/8d2dc538-74ef-11e6-9ac4-17517de71dd3.jpg)

**Comment by jeffreyolchovy** [comment]
If you haven't begun work on this, I can take a look at it this coming weekend. We are solving the sbt-release + sbt-doge integration issue at Tapad for a number of internal projects that contain both a library and a plugin. We use both plugins (doge and release) successfully in isolation and are now pained with an extra manual step when a project needs to include both.

**Comment by dwijnand** [comment]
Have a look at https://github.com/dwijnand/releash where I tried to figure this out.

@eed3si9n recommends the best way is to copy the implementation of sbt-doge into sbt-release and use its mechanism of aggregating projects over sbt's way.
