### ISSUE TITLE
json4s Facade maps int to JDouble

### ISSUE THREAD

**Issue by fadeddata** [non/jawn#62]
This seems to be incorrect to me.

https://github.com/non/jawn/blob/1346dca2725e41f2b2672363e5b19c2a8ba39d7a/support/json4s/src/main/scala/Parser.scala#L15

Should it not be:

```
      def jint(s: String) = JInt(java.lang.Integer.parseInt(s))
```

**Comment by non** [comment]
Yes, good catch! Maybe I didn't realize that `JInt` existed when I wrote that.

Feel like submitting a PR? If not I can fix this later tonight.

**Comment by tapmania** [comment]
@non Here is the PR: https://github.com/non/jawn/pull/66

**Comment by non** [comment]
Thanks for the PR!
