### ISSUE TITLE
Update support library versions

### ISSUE THREAD

**Issue by non** [non/jawn#65]
When we update to 0.11.0 we should bump the following library versions:

 * Play-JSON: 2.5.9
 * Rojoma-V3: 3.7.0
 * json4s: 3.5.0

(I will add to this list as new versions are discovered.)

We should also consider dropping Rojoma v2 and standardizing on Rojomva v3.

**Comment by rossabaker** [comment]
json4s-3.5.0 is coming soon.

**Comment by non** [comment]
Fixed in 0.10.4.
