### ISSUE TITLE
Release for Scala 2.13

### ISSUE THREAD

**Issue by dwijnand** [non/jawn#97]
https://github.com/non/jawn/pull/86 added support for 2.13.0-M1, but it doesn't look like a 2.13 version of jawn was released: http://repo1.maven.org/maven2/org/spire-math/ (also 2.13.0-M2 is out)

**Comment by SethTisue** [comment]
Scala 2.13.0-M3 is now out.

**Comment by non** [comment]
Just released 0.12.1 with 2.13.0-M3 support.
